Fix bug in naming of Sentry release
In #3299 sentry-ruby was updated past 5.10 which introduces
getsentry/sentry-ruby#2004, resulting in:

    ArgumentError: expect the argument to be a String or NilClass, got Integer (1646633480)
    /osem/config/initializers/sentry.rb:19